//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Dreamteck.Splines.SplineTrigger.TriggerEvent))]
	public class PropertyProvider_Dreamteck_Splines_SplineTrigger_TriggerEvent : Unity.VisualScripting.SerializedPropertyProvider<Dreamteck.Splines.SplineTrigger.TriggerEvent>
	{
	}
}
